packages:
  - apps/*
  - packages/*
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  prisma: true
  esbuild: true
  embedded-postgres: true
  '@embedded-postgres/windows-x64': true
  '@embedded-postgres/linux-x64': true
  '@embedded-postgres/linux-arm64': true
  '@embedded-postgres/darwin-x64': true
  '@embedded-postgres/darwin-arm64': true
  '@nestjs/core': true
overrides:
  '@prisma/config>deepmerge-ts': 8.0.2
